---
- hosts: all
  become: true
  remote_user: root


  tasks:
  - name: Check RPMs
    redhat_check_yum_pkgs:
      pkgs: ['screen','yum','glibc','openssh','ncurses']
      state: present
    register: response
 
  - debug: var=response
